package eu.opentxs.bridge;

public enum Text {
	CONSOLE_TITLE, WELCOME_HEADER, WELCOME_CREDITS,

	FEATURE_UNSUPPORTED_YET, FEATURE_DISABLED_SERVER_BUG, NAME_UNKNOWN,

	COMMAND_UNKNOWN, COMMAND_ABORTED, COMMAND_ENDED_WITH_SUCCESS, COMMAND_ENDED_WITH_ERROR,

	VALIDATION_MUST_BE_BOOLEAN, VALIDATION_MUST_BE_DATE, VALIDATION_MUST_BE_DATE_FUTURE, VALIDATION_MUST_BE_NUMBER, VALIDATION_MUST_BE_NUMBER_RANGE, VALIDATION_MUST_BE_INTEGER, VALIDATION_MUST_BE_INTEGER_RANGE, VALIDATION_MUST_BE_ID, VALIDATION_MUST_BE_INTEGER_OR_ID, VALIDATION_MUST_BE_INTEGER_LIST, VALIDATION_MUST_BE_INTEGER_LIST_RANGE,

	EMPTY_ARGUMENT_ERROR,

	INTEGER_EXPECTED_ERROR, INTEGER_LIST_EXPECTED_ERROR, FLOAT_EXPECTED_ERROR, DOUBLE_EXPECTED_ERROR, DATE_EXPECTED_ERROR,

	INTEGER_LIST_SEPARATOR,

	PARSE_SERVER_ID_ERROR, PARSE_NYM_ID_ERROR, PARSE_ASSET_ID_ERROR, PARSE_ACCOUNT_ID_ERROR,

	SERVER_ID, NYM_ID, ASSET_ID, ACCOUNT_ID,

	FOLDER_SERVERS, FOLDER_NYMS, FOLDER_ASSETS, FOLDER_CHEQUES, FOLDER_CASH,

	OPEN_FILE_TITLE, OPEN_FILE, SAVE_FILE_TITLE, SAVE_FILE, FILE_DOES_NOT_EXIST_TITLE, FILE_DOES_NOT_EXIST, FILE_OVERWRITE_TITLE, FILE_OVERWRITE, FILE_SAVED_AS,

	ISSUER_SIGN,

	BANK, SERVER, NAME,

	ME, MY_NYM, MY_ASSET, MY_ACCOUNT, HE, HIS_NYM, HIS_ASSET, HIS_ACCOUNT,

	WARN, SKIP, SUCCESS,

	VERIFYING_REQUEST, REQUEST_ID_ZERO, REQUEST_ID_NEGATIVE, RECEIVING_MESSAGE, MESSAGE_IS_INVALID, VERIFYING_MESSAGE, MESSAGE_VERIFICATION_ERROR, MESSAGE_VERIFICATION_FAILED, TRANSACTION_MESSAGE_IS_INVALID, VERIFYING_BALANCE_AGREEMENT, BALANCE_AGREEMENT_ERROR, VERIFYING_TRANSACTION_MESSAGE, TRANSACTION_MESSAGE_VERIFICATION_ERROR, STRING_TO_DOUBLE_CONVERSION_ERROR, NYM_NEEEDS_TO_REGISTERED_ERROR, ;

	@Override
	public String toString() {
		return Localizer.get().getString(name());
	}
}
